// Hand-curated mock catalog. ~60 items across budget/mid/premium/luxury tiers.
// Each item is written in the abstract — color + type + vibe — so the
// recommendation engine can reason about it without brand bias.
//
// tier: 'budget' = Uniqlo-ish, 'mid' = Zara / Nike / Adidas / Timberland,
//       'premium' = SSENSE designer & Salomon, 'luxury' = Cartier / Van Cleef
// gender: 'men' | 'women' | 'unisex'
// palette: which undertones the color flatters
// styles: aesthetic tags — 'minimalist','streetwear','gothic','y2k',
//         'gorpcore','workwear','preppy'

export const CATALOG = [
  // ——— BUDGET (Uniqlo / Muji / COS basics) ———
  {
    id: "u-tee-cream",
    name: "Supima Crew Tee",
    brand: "Uniqlo",
    type: "top",
    subtype: "t-shirt",
    color: "#ECE5D3",
    palette: ["warm", "neutral"],
    tier: "budget",
    price: 19.9,
    gender: "unisex",
    occasions: ["casual", "date", "gym"],
    fit: ["slim", "regular"],
    styles: ["minimalist", "preppy"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-tee-ink",
    name: "Heavyweight Boxy Tee",
    brand: "Uniqlo U",
    type: "top",
    subtype: "t-shirt",
    color: "#0f0e0c",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 24.9,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["regular", "loose", "oversized"],
    styles: ["minimalist", "streetwear", "gothic"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-ox-white",
    name: "Oxford Shirt",
    brand: "Uniqlo",
    type: "top",
    subtype: "shirt",
    color: "#F3EFE6",
    palette: ["warm", "cool", "neutral"],
    tier: "budget",
    price: 39.9,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["slim", "regular"],
    styles: ["minimalist", "preppy", "workwear"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-knit-rust",
    name: "Merino Crew Knit",
    brand: "Uniqlo",
    type: "top",
    subtype: "knit",
    color: "#B45A3C",
    palette: ["warm"],
    tier: "budget",
    price: 49.9,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["slim", "regular"],
    styles: ["minimalist", "preppy"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-knit-navy",
    name: "Merino Crew Knit",
    brand: "Uniqlo",
    type: "top",
    subtype: "knit",
    color: "#1C2E4A",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 49.9,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["slim", "regular"],
    styles: ["minimalist", "preppy"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-hoodie-ink",
    name: "Sweat Pullover Hoodie",
    brand: "Uniqlo",
    type: "top",
    subtype: "hoodie",
    color: "#0f0e0c",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 39.9,
    gender: "unisex",
    occasions: ["casual", "gym"],
    fit: ["regular", "loose"],
    styles: ["streetwear", "minimalist", "gothic"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-hoodie-sage",
    name: "Oversized Hoodie",
    brand: "Uniqlo U",
    type: "top",
    subtype: "hoodie",
    color: "#8BA68B",
    palette: ["warm", "neutral"],
    tier: "budget",
    price: 49.9,
    gender: "unisex",
    occasions: ["casual"],
    fit: ["loose", "oversized"],
    styles: ["minimalist", "streetwear", "gorpcore"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-jean-indigo",
    name: "Regular Fit Jean",
    brand: "Uniqlo",
    type: "bottom",
    subtype: "jeans",
    color: "#2C3E50",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 49.9,
    gender: "men",
    occasions: ["casual", "date", "party"],
    fit: ["slim", "regular"],
    styles: ["minimalist", "preppy", "workwear"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-chino-stone",
    name: "Wide Chino",
    brand: "Uniqlo U",
    type: "bottom",
    subtype: "chinos",
    color: "#C2B7A3",
    palette: ["warm", "neutral"],
    tier: "budget",
    price: 49.9,
    gender: "unisex",
    occasions: ["work", "casual"],
    fit: ["regular", "loose"],
    styles: ["minimalist", "preppy", "workwear"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-short-black",
    name: "Ultra-Stretch Dry Short",
    brand: "Uniqlo",
    type: "bottom",
    subtype: "shorts",
    color: "#1A1916",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 29.9,
    gender: "unisex",
    occasions: ["gym", "casual"],
    fit: ["slim", "regular"],
    styles: ["minimalist"],
    url: "https://www.uniqlo.com/",
  },
  {
    id: "u-sk-white",
    name: "Canvas Low Sneaker",
    brand: "Muji",
    type: "shoes",
    subtype: "sneakers",
    color: "#F6F2EA",
    palette: ["warm", "cool", "neutral"],
    tier: "budget",
    price: 59,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["any"],
    styles: ["minimalist", "preppy"],
    url: "https://www.muji.com/",
  },

  // ——— MID (Zara / COS / Arket / Nike / Adidas / Timberland) ———
  {
    id: "z-ovr-olive",
    name: "Oversized Crewneck",
    brand: "Zara",
    type: "top",
    subtype: "sweatshirt",
    color: "#6B8E4E",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 59,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["loose", "oversized"],
    styles: ["streetwear", "gorpcore"],
    url: "https://www.zara.com/",
  },
  {
    id: "z-hoodie-black",
    name: "Washed Cotton Hoodie",
    brand: "Zara",
    type: "top",
    subtype: "hoodie",
    color: "#151311",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 59,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["regular", "loose", "oversized"],
    styles: ["streetwear", "gothic"],
    url: "https://www.zara.com/",
  },
  {
    id: "z-overshirt-black",
    name: "Wool-blend Overshirt",
    brand: "Zara",
    type: "outerwear",
    subtype: "overshirt",
    color: "#151311",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 89,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["regular", "loose"],
    styles: ["minimalist", "workwear", "gothic"],
    url: "https://www.zara.com/",
  },
  {
    id: "z-knit-burg",
    name: "Cashmere-blend Knit",
    brand: "COS",
    type: "top",
    subtype: "knit",
    color: "#8B2C5F",
    palette: ["cool"],
    tier: "mid",
    price: 110,
    gender: "women",
    occasions: ["work", "date"],
    fit: ["regular"],
    styles: ["minimalist", "preppy"],
    url: "https://www.cos.com/",
  },
  {
    id: "z-trouser-chrc",
    name: "Pleated Wool Trouser",
    brand: "COS",
    type: "bottom",
    subtype: "trousers",
    color: "#2A2A2A",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 135,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["regular", "loose"],
    styles: ["minimalist", "workwear", "gothic"],
    url: "https://www.cos.com/",
  },
  {
    id: "z-trouser-cream",
    name: "Linen Wide Trouser",
    brand: "Arket",
    type: "bottom",
    subtype: "trousers",
    color: "#E8E0CE",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 129,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["loose", "oversized"],
    styles: ["minimalist", "preppy"],
    url: "https://www.arket.com/",
  },
  {
    id: "z-skirt-plum",
    name: "Bias-cut Satin Skirt",
    brand: "Zara",
    type: "bottom",
    subtype: "skirt",
    color: "#8B2C5F",
    palette: ["cool"],
    tier: "mid",
    price: 79,
    gender: "women",
    occasions: ["date", "party"],
    fit: ["regular"],
    styles: ["y2k", "minimalist"],
    url: "https://www.zara.com/",
  },
  {
    id: "z-dress-camel",
    name: "Wrap Midi Dress",
    brand: "Zara",
    type: "top", // acts as top+bottom; we'll treat as a full piece (see outfitBuilder)
    subtype: "dress",
    color: "#D4B483",
    palette: ["warm"],
    tier: "mid",
    price: 99,
    gender: "women",
    occasions: ["date", "work", "party"],
    fit: ["regular"],
    styles: ["minimalist", "preppy"],
    url: "https://www.zara.com/",
  },
  {
    id: "z-sk-leather",
    name: "Leather Court Sneaker",
    brand: "COS",
    type: "shoes",
    subtype: "sneakers",
    color: "#F3EFE6",
    palette: ["warm", "cool", "neutral"],
    tier: "mid",
    price: 160,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["any"],
    styles: ["minimalist", "preppy"],
    url: "https://www.cos.com/",
  },
  {
    id: "z-boot-brown",
    name: "Chelsea Boot",
    brand: "Arket",
    type: "shoes",
    subtype: "boots",
    color: "#4A3828",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 225,
    gender: "unisex",
    occasions: ["work", "date", "casual"],
    fit: ["any"],
    styles: ["workwear", "preppy", "minimalist"],
    url: "https://www.arket.com/",
  },
  {
    id: "z-coat-camel",
    name: "Relaxed Wool Coat",
    brand: "Zara",
    type: "outerwear",
    subtype: "coat",
    color: "#C48B3F",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 229,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["regular", "loose"],
    styles: ["minimalist", "preppy"],
    url: "https://www.zara.com/",
  },

  // ——— Nike ———
  {
    id: "n-af1-white",
    name: "Air Force 1 '07",
    brand: "Nike",
    type: "shoes",
    subtype: "sneakers",
    color: "#F3EFE6",
    palette: ["warm", "cool", "neutral"],
    tier: "mid",
    price: 115,
    gender: "unisex",
    occasions: ["casual", "party", "date"],
    fit: ["any"],
    styles: ["streetwear", "minimalist"],
    url: "https://www.nike.com/",
  },
  {
    id: "n-dunk-black",
    name: "Dunk Low",
    brand: "Nike",
    type: "shoes",
    subtype: "sneakers",
    color: "#0f0e0c",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 120,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["streetwear", "y2k"],
    url: "https://www.nike.com/",
  },
  {
    id: "n-am90-grey",
    name: "Air Max 90",
    brand: "Nike",
    type: "shoes",
    subtype: "sneakers",
    color: "#A6A6A6",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 140,
    gender: "unisex",
    occasions: ["casual", "gym"],
    fit: ["any"],
    styles: ["streetwear", "gorpcore", "y2k"],
    url: "https://www.nike.com/",
  },
  {
    id: "n-killshot-navy",
    name: "Killshot 2",
    brand: "Nike",
    type: "shoes",
    subtype: "sneakers",
    color: "#1C2E4A",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 95,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["any"],
    styles: ["preppy", "minimalist"],
    url: "https://www.nike.com/",
  },

  // ——— Adidas ———
  {
    id: "a-samba-black",
    name: "Samba OG",
    brand: "Adidas",
    type: "shoes",
    subtype: "sneakers",
    color: "#0f0e0c",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 100,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["any"],
    styles: ["streetwear", "preppy", "minimalist"],
    url: "https://www.adidas.com/",
  },
  {
    id: "a-gazelle-green",
    name: "Gazelle",
    brand: "Adidas",
    type: "shoes",
    subtype: "sneakers",
    color: "#0C4A2A",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 100,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["streetwear", "y2k"],
    url: "https://www.adidas.com/",
  },
  {
    id: "a-superstar-white",
    name: "Superstar",
    brand: "Adidas",
    type: "shoes",
    subtype: "sneakers",
    color: "#F3EFE6",
    palette: ["warm", "cool", "neutral"],
    tier: "mid",
    price: 110,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["streetwear", "y2k", "preppy"],
    url: "https://www.adidas.com/",
  },

  // ——— Timberland ———
  {
    id: "t-prem-wheat",
    name: "Premium 6\" Waterproof Boot",
    brand: "Timberland",
    type: "shoes",
    subtype: "boots",
    color: "#C19A6B",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 200,
    gender: "unisex",
    occasions: ["casual", "work"],
    fit: ["any"],
    styles: ["workwear", "streetwear", "gorpcore"],
    url: "https://www.timberland.com/",
  },
  {
    id: "t-chelsea-black",
    name: "Courma Chelsea Boot",
    brand: "Timberland",
    type: "shoes",
    subtype: "boots",
    color: "#0f0e0c",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 195,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["any"],
    styles: ["workwear", "gothic", "minimalist"],
    url: "https://www.timberland.com/",
  },

  // ——— PREMIUM (SSENSE / Our Legacy / Lemaire / Acne / Carhartt WIP / ALD / Stüssy / Salomon) ———
  {
    id: "s-hoodie-cream",
    name: "Hooded Sweatshirt",
    brand: "Carhartt WIP",
    type: "top",
    subtype: "hoodie",
    color: "#E8DDC6",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 145,
    gender: "unisex",
    occasions: ["casual"],
    fit: ["loose", "oversized"],
    styles: ["streetwear", "workwear"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-hoodie-rust",
    name: "Logo Hoodie",
    brand: "Aimé Leon Dore",
    type: "top",
    subtype: "hoodie",
    color: "#A64B2B",
    palette: ["warm"],
    tier: "premium",
    price: 295,
    gender: "unisex",
    occasions: ["casual"],
    fit: ["regular", "loose"],
    styles: ["streetwear", "preppy"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-hoodie-olive",
    name: "Stock Logo Hoodie",
    brand: "Stüssy",
    type: "top",
    subtype: "hoodie",
    color: "#5E6B3A",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 150,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["loose", "oversized"],
    styles: ["streetwear", "gorpcore"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-knit-mustard",
    name: "Box Knit in Wool",
    brand: "Our Legacy",
    type: "top",
    subtype: "knit",
    color: "#C48B3F",
    palette: ["warm"],
    tier: "premium",
    price: 345,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["loose", "oversized"],
    styles: ["minimalist", "workwear"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-shirt-sage",
    name: "Silk-blend Shirt",
    brand: "Lemaire",
    type: "top",
    subtype: "shirt",
    color: "#8BA68B",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 465,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["regular", "loose"],
    styles: ["minimalist"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-trouser-choco",
    name: "Twisted Seam Trouser",
    brand: "Lemaire",
    type: "bottom",
    subtype: "trousers",
    color: "#463D33",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 625,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["loose"],
    styles: ["minimalist", "workwear"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-jean-bleach",
    name: "Bleached Denim Jean",
    brand: "Acne Studios",
    type: "bottom",
    subtype: "jeans",
    color: "#98B4B7",
    palette: ["cool"],
    tier: "premium",
    price: 395,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["loose", "oversized"],
    styles: ["y2k", "streetwear"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-jacket-navy",
    name: "Unstructured Wool Blazer",
    brand: "Auralee",
    type: "outerwear",
    subtype: "blazer",
    color: "#1C2E4A",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 895,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["regular", "loose"],
    styles: ["minimalist", "preppy", "workwear"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-sk-suede",
    name: "Suede Runner",
    brand: "Adidas × Wales Bonner",
    type: "shoes",
    subtype: "sneakers",
    color: "#7A5E3B",
    palette: ["warm"],
    tier: "premium",
    price: 275,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["any"],
    styles: ["preppy", "streetwear"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-loafer-black",
    name: "Penny Loafer",
    brand: "G.H. Bass",
    type: "shoes",
    subtype: "loafers",
    color: "#0f0e0c",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 245,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["any"],
    styles: ["preppy", "minimalist"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-tee-stone",
    name: "Heavy Cotton Tee",
    brand: "Lady White Co.",
    type: "top",
    subtype: "t-shirt",
    color: "#A69D8A",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 120,
    gender: "unisex",
    occasions: ["casual", "gym", "date"],
    fit: ["regular", "loose"],
    styles: ["minimalist"],
    url: "https://www.ssense.com/",
  },
  {
    id: "s-dress-ink",
    name: "Column Slip Dress",
    brand: "The Row",
    type: "top",
    subtype: "dress",
    color: "#0f0e0c",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 1290,
    gender: "women",
    occasions: ["date", "party", "formal"],
    fit: ["slim", "regular"],
    styles: ["minimalist", "gothic"],
    url: "https://www.ssense.com/",
  },

  // ——— Salomon (premium trail/tech sneakers via SSENSE) ———
  {
    id: "sa-xt6-black",
    name: "XT-6",
    brand: "Salomon",
    type: "shoes",
    subtype: "sneakers",
    color: "#1A1A1A",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 225,
    gender: "unisex",
    occasions: ["casual", "gym"],
    fit: ["any"],
    styles: ["gorpcore", "streetwear", "gothic"],
    url: "https://www.ssense.com/",
  },
  {
    id: "sa-xapro-olive",
    name: "XA Pro 3D",
    brand: "Salomon",
    type: "shoes",
    subtype: "sneakers",
    color: "#4A4E2A",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 170,
    gender: "unisex",
    occasions: ["casual", "gym"],
    fit: ["any"],
    styles: ["gorpcore", "streetwear"],
    url: "https://www.ssense.com/",
  },
  {
    id: "sa-acs-silver",
    name: "ACS Pro Advanced",
    brand: "Salomon",
    type: "shoes",
    subtype: "sneakers",
    color: "#C8C8CC",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 225,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["gorpcore", "y2k", "streetwear"],
    url: "https://www.ssense.com/",
  },

  // ——— MUSINSA-CORE EXPANSION ———
  // Korean-style board: neutral palette, relaxed+tailored proportions,
  // knits-over-shirts, wide trousers, white leather sneakers, loafers.

  // Streetwear additions — Jaded London / Kiff / Ellwood / Acne (extras)
  {
    id: "jl-carpenter-stone",
    name: "Colossus Carpenter Jean",
    brand: "Jaded London",
    type: "bottom",
    subtype: "jeans",
    color: "#C2B7A3",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 95,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["loose", "oversized"],
    styles: ["streetwear", "y2k", "workwear"],
    url: "https://www.jadedldn.com/",
  },
  {
    id: "jl-graphic-tee",
    name: "Oversized Graphic Tee",
    brand: "Jaded London",
    type: "top",
    subtype: "t-shirt",
    color: "#151311",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 60,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["loose", "oversized"],
    styles: ["streetwear", "y2k"],
    url: "https://www.jadedldn.com/",
  },
  {
    id: "kf-tech-hoodie",
    name: "Tech Fleece Hoodie",
    brand: "Kiff",
    type: "top",
    subtype: "hoodie",
    color: "#2A2A2A",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 195,
    gender: "unisex",
    occasions: ["casual", "gym"],
    fit: ["regular", "loose"],
    styles: ["streetwear", "gorpcore"],
    url: "https://kiff.studio/",
  },
  {
    id: "ew-denim-jacket",
    name: "Washed Denim Jacket",
    brand: "Ellwood",
    type: "outerwear",
    subtype: "overshirt",
    color: "#2C3E50",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 280,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["regular", "loose"],
    styles: ["streetwear", "workwear"],
    url: "https://ellwood.nyc/",
  },
  {
    id: "ac-face-sweater",
    name: "Face Logo Sweatshirt",
    brand: "Acne Studios",
    type: "top",
    subtype: "sweatshirt",
    color: "#A69D8A",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 420,
    gender: "unisex",
    occasions: ["casual", "date"],
    fit: ["regular", "loose", "oversized"],
    styles: ["streetwear", "minimalist"],
    url: "https://www.ssense.com/",
  },

  // Preppy additions — Mango / Massimo Dutti / Suitsupply
  {
    id: "mg-linen-blazer",
    name: "Linen Unstructured Blazer",
    brand: "Mango",
    type: "outerwear",
    subtype: "blazer",
    color: "#E8DDC6",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 160,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["regular", "loose"],
    styles: ["preppy", "minimalist"],
    url: "https://shop.mango.com/",
  },
  {
    id: "mg-cotton-polo",
    name: "Fine-gauge Cotton Polo",
    brand: "Mango",
    type: "top",
    subtype: "knit",
    color: "#1C2E4A",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 50,
    gender: "unisex",
    occasions: ["casual", "work", "date"],
    fit: ["slim", "regular"],
    styles: ["preppy", "minimalist"],
    url: "https://shop.mango.com/",
  },
  {
    id: "mg-pleat-skirt",
    name: "Pleated Midi Skirt",
    brand: "Mango",
    type: "bottom",
    subtype: "skirt",
    color: "#5E6B3A",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 70,
    gender: "women",
    occasions: ["work", "date", "casual"],
    fit: ["regular"],
    styles: ["preppy", "minimalist"],
    url: "https://shop.mango.com/",
  },
  {
    id: "md-wool-trouser",
    name: "Pleated Wool Trouser",
    brand: "Massimo Dutti",
    type: "bottom",
    subtype: "trousers",
    color: "#2A2A2A",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 170,
    gender: "unisex",
    occasions: ["work", "date", "formal"],
    fit: ["regular", "loose"],
    styles: ["preppy", "workwear", "minimalist"],
    url: "https://www.massimodutti.com/",
  },
  {
    id: "md-cashmere-cardigan",
    name: "Cashmere V-Neck Cardigan",
    brand: "Massimo Dutti",
    type: "top",
    subtype: "knit",
    color: "#D7CCB3",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 250,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["regular"],
    styles: ["preppy", "minimalist"],
    url: "https://www.massimodutti.com/",
  },
  {
    id: "md-suede-loafer",
    name: "Suede Penny Loafer",
    brand: "Massimo Dutti",
    type: "shoes",
    subtype: "loafers",
    color: "#4A3828",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 220,
    gender: "unisex",
    occasions: ["work", "date", "casual"],
    fit: ["any"],
    styles: ["preppy", "minimalist"],
    url: "https://www.massimodutti.com/",
  },
  {
    id: "ss-cotton-chino",
    name: "Cotton Chino",
    brand: "Suitsupply",
    type: "bottom",
    subtype: "chinos",
    color: "#C2B7A3",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 195,
    gender: "men",
    occasions: ["work", "casual", "date"],
    fit: ["slim", "regular"],
    styles: ["preppy", "minimalist", "workwear"],
    url: "https://suitsupply.com/",
  },
  {
    id: "ss-navy-blazer",
    name: "Navy Hopsack Blazer",
    brand: "Suitsupply",
    type: "outerwear",
    subtype: "blazer",
    color: "#1C2E4A",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 499,
    gender: "men",
    occasions: ["work", "date", "formal"],
    fit: ["slim", "regular"],
    styles: ["preppy", "workwear", "minimalist"],
    url: "https://suitsupply.com/",
  },

  // Minimalist additions — NN.07 / COS (extras)
  {
    id: "nn-clive-crew",
    name: "Clive Merino Crewneck",
    brand: "NN.07",
    type: "top",
    subtype: "knit",
    color: "#E8DDC6",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 240,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["regular"],
    styles: ["minimalist", "preppy"],
    url: "https://www.ssense.com/",
  },
  {
    id: "nn-linen-trouser",
    name: "Pleated Linen Trouser",
    brand: "NN.07",
    type: "bottom",
    subtype: "trousers",
    color: "#5E6B3A",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 210,
    gender: "unisex",
    occasions: ["casual", "work", "date"],
    fit: ["loose"],
    styles: ["minimalist", "gorpcore"],
    url: "https://www.ssense.com/",
  },
  {
    id: "cos-cashmere-oversized",
    name: "Oversized Cashmere Sweater",
    brand: "COS",
    type: "top",
    subtype: "knit",
    color: "#1C2E4A",
    palette: ["cool", "neutral"],
    tier: "mid",
    price: 250,
    gender: "unisex",
    occasions: ["work", "casual", "date"],
    fit: ["loose", "oversized"],
    styles: ["minimalist", "preppy"],
    url: "https://www.cos.com/",
  },

  // ——— JEWELRY ———
  // Budget (Amazon / Kurth / Yordy) — cheap picks, gothic-heavy.
  {
    id: "az-hoop-gold",
    name: "Stainless Steel Hoop Earrings",
    brand: "Amazon Essentials",
    type: "jewelry",
    subtype: "earrings",
    color: "#D4B483",
    palette: ["warm", "neutral"],
    tier: "budget",
    price: 12,
    gender: "women",
    occasions: ["casual", "date", "party", "gym"],
    fit: ["any"],
    styles: ["minimalist", "y2k"],
    url: "https://www.amazon.com/",
  },
  {
    id: "az-layered-chain",
    name: "Layered Chain Necklace Set",
    brand: "Amazon",
    type: "jewelry",
    subtype: "necklace",
    color: "#C0C0C8",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 15,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["streetwear", "y2k", "gothic"],
    url: "https://www.amazon.com/",
  },
  {
    id: "az-band-ring-set",
    name: "Simple Band Ring Set (3-pack)",
    brand: "Amazon",
    type: "jewelry",
    subtype: "ring",
    color: "#D4B483",
    palette: ["warm", "neutral"],
    tier: "budget",
    price: 18,
    gender: "unisex",
    occasions: ["casual", "work", "date"],
    fit: ["any"],
    styles: ["minimalist"],
    url: "https://www.amazon.com/",
  },
  {
    id: "az-snake-bracelet",
    name: "Snake Chain Bracelet",
    brand: "Amazon",
    type: "jewelry",
    subtype: "bracelet",
    color: "#C0C0C8",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 14,
    gender: "unisex",
    occasions: ["casual", "date", "party"],
    fit: ["any"],
    styles: ["minimalist", "streetwear"],
    url: "https://www.amazon.com/",
  },
  {
    id: "az-onyx-stud",
    name: "Black Onyx Stud Earrings",
    brand: "Amazon",
    type: "jewelry",
    subtype: "earrings",
    color: "#1A1A1A",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 10,
    gender: "unisex",
    occasions: ["casual", "work", "date"],
    fit: ["any"],
    styles: ["gothic", "minimalist"],
    url: "https://www.amazon.com/",
  },
  {
    id: "kh-skull-ring",
    name: "Skull Signet Ring",
    brand: "Kurth",
    type: "jewelry",
    subtype: "ring",
    color: "#8A8A92",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 45,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["gothic", "streetwear"],
    url: "https://kurthjewelry.com/",
  },
  {
    id: "kh-cross-necklace",
    name: "Oxidized Cross Pendant",
    brand: "Kurth",
    type: "jewelry",
    subtype: "necklace",
    color: "#6A6A72",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 60,
    gender: "unisex",
    occasions: ["casual", "party", "date"],
    fit: ["any"],
    styles: ["gothic", "streetwear"],
    url: "https://kurthjewelry.com/",
  },
  {
    id: "kh-curb-bracelet",
    name: "Heavy Curb Chain Bracelet",
    brand: "Kurth",
    type: "jewelry",
    subtype: "bracelet",
    color: "#8A8A92",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 75,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["gothic", "streetwear"],
    url: "https://kurthjewelry.com/",
  },
  {
    id: "kh-thorn-ring",
    name: "Thorn Ring",
    brand: "Kurth",
    type: "jewelry",
    subtype: "ring",
    color: "#4A4A52",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 55,
    gender: "unisex",
    occasions: ["casual", "party", "date"],
    fit: ["any"],
    styles: ["gothic"],
    url: "https://kurthjewelry.com/",
  },
  {
    id: "yd-cross-earrings",
    name: "Gothic Cross Drop Earrings",
    brand: "Yordy",
    type: "jewelry",
    subtype: "earrings",
    color: "#8A8A92",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 35,
    gender: "unisex",
    occasions: ["casual", "party", "date"],
    fit: ["any"],
    styles: ["gothic"],
    url: "https://yordy.co/",
  },
  {
    id: "yd-spike-ring",
    name: "Spike Stack Ring",
    brand: "Yordy",
    type: "jewelry",
    subtype: "ring",
    color: "#6A6A72",
    palette: ["cool", "neutral"],
    tier: "budget",
    price: 40,
    gender: "unisex",
    occasions: ["casual", "party"],
    fit: ["any"],
    styles: ["gothic", "streetwear"],
    url: "https://yordy.co/",
  },
  {
    id: "yd-pearl-chain",
    name: "Pearl & Chain Necklace",
    brand: "Yordy",
    type: "jewelry",
    subtype: "necklace",
    color: "#E8E0D2",
    palette: ["warm", "neutral"],
    tier: "budget",
    price: 85,
    gender: "unisex",
    occasions: ["casual", "date", "party"],
    fit: ["any"],
    styles: ["gothic", "y2k"],
    url: "https://yordy.co/",
  },

  // Mid (Mejuri) — accessible every-day gold.
  {
    id: "me-hoop-gold",
    name: "Bold Hoop",
    brand: "Mejuri",
    type: "jewelry",
    subtype: "earrings",
    color: "#D4B483",
    palette: ["warm", "neutral"],
    tier: "mid",
    price: 150,
    gender: "women",
    occasions: ["casual", "date", "party", "work"],
    fit: ["any"],
    styles: ["minimalist", "y2k", "preppy"],
    url: "https://mejuri.com/",
  },

  // Premium (Margiela / Tom Wood / Ambush / Dries — via SSENSE)
  {
    id: "m-fourstitch-silver",
    name: "Four-Stitch Ring",
    brand: "Maison Margiela",
    type: "jewelry",
    subtype: "ring",
    color: "#C0C0C8",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 315,
    gender: "unisex",
    occasions: ["casual", "date", "party", "work"],
    fit: ["any"],
    styles: ["minimalist", "gothic"],
    url: "https://www.ssense.com/",
  },
  {
    id: "m-splitband-silver",
    name: "Split Band Ring",
    brand: "Maison Margiela",
    type: "jewelry",
    subtype: "ring",
    color: "#C0C0C8",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 285,
    gender: "unisex",
    occasions: ["casual", "date", "work"],
    fit: ["any"],
    styles: ["minimalist", "gothic"],
    url: "https://www.ssense.com/",
  },
  {
    id: "tw-chunky-silver",
    name: "Chunky Cushion Ring",
    brand: "Tom Wood",
    type: "jewelry",
    subtype: "ring",
    color: "#C0C0C8",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 345,
    gender: "unisex",
    occasions: ["casual", "date", "party"],
    fit: ["any"],
    styles: ["minimalist", "gothic"],
    url: "https://www.ssense.com/",
  },
  {
    id: "amb-chain-silver",
    name: "Classic Chain Necklace",
    brand: "Ambush",
    type: "jewelry",
    subtype: "necklace",
    color: "#B0B0B8",
    palette: ["cool", "neutral"],
    tier: "premium",
    price: 595,
    gender: "unisex",
    occasions: ["casual", "party", "date"],
    fit: ["any"],
    styles: ["streetwear", "gothic", "y2k"],
    url: "https://www.ssense.com/",
  },
  {
    id: "dvn-brass-necklace",
    name: "Brass Pendant Necklace",
    brand: "Dries Van Noten",
    type: "jewelry",
    subtype: "necklace",
    color: "#A8804A",
    palette: ["warm", "neutral"],
    tier: "premium",
    price: 410,
    gender: "unisex",
    occasions: ["date", "party", "work"],
    fit: ["any"],
    styles: ["minimalist"],
    url: "https://www.ssense.com/",
  },

  // Luxury (Cartier / Van Cleef & Arpels)
  {
    id: "c-love-gold",
    name: "Love Bracelet",
    brand: "Cartier",
    type: "jewelry",
    subtype: "bracelet",
    color: "#D4B483",
    palette: ["warm", "neutral"],
    tier: "luxury",
    price: 7350,
    gender: "unisex",
    occasions: ["date", "party", "work", "formal", "casual"],
    fit: ["any"],
    styles: ["minimalist", "preppy"],
    url: "https://www.cartier.com/",
  },
  {
    id: "c-juste-gold",
    name: "Juste un Clou Ring",
    brand: "Cartier",
    type: "jewelry",
    subtype: "ring",
    color: "#D4B483",
    palette: ["warm", "neutral"],
    tier: "luxury",
    price: 1800,
    gender: "unisex",
    occasions: ["date", "party", "work", "casual"],
    fit: ["any"],
    styles: ["minimalist", "streetwear"],
    url: "https://www.cartier.com/",
  },
  {
    id: "vc-alhambra-gold",
    name: "Vintage Alhambra Pendant",
    brand: "Van Cleef & Arpels",
    type: "jewelry",
    subtype: "necklace",
    color: "#E8C072",
    palette: ["warm"],
    tier: "luxury",
    price: 2820,
    gender: "women",
    occasions: ["date", "party", "work", "formal"],
    fit: ["any"],
    styles: ["preppy", "minimalist"],
    url: "https://www.vancleefarpels.com/",
  },
  {
    id: "vc-perlee-gold",
    name: "Perlée Signature Bracelet",
    brand: "Van Cleef & Arpels",
    type: "jewelry",
    subtype: "bracelet",
    color: "#D4B483",
    palette: ["warm", "neutral"],
    tier: "luxury",
    price: 4250,
    gender: "women",
    occasions: ["date", "party", "formal"],
    fit: ["any"],
    styles: ["minimalist", "preppy"],
    url: "https://www.vancleefarpels.com/",
  },
];

// helpers
export const byId = (id) => CATALOG.find((i) => i.id === id);
export const tierOf = (budgetPref) =>
  budgetPref === "uniqlo" ? "budget" : budgetPref === "zara" ? "mid" : "premium";

// ordinal distance between tiers — used for scoring & compatibility
export const TIER_RANK = { budget: 0, mid: 1, premium: 2, luxury: 3 };
